[book]
authors = ["duykhanh471"]
language = "vi"
multilingual = false
src = "src"
title = "Đắm mình vào hệ thống - Dive into Systems"

[build]
build-dir = "public"

[output.html]
mathjax-support = true